language: python

matrix:
  include:
    - python: 2.7
      env: KERAS_BACKEND=theano

notifications:
  email: false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-4.3.31-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - conda env create -f conda_env.yml
  - source activate pria
  - conda list

install:
  - pip install -e .

script:
  - python -c "import keras.backend"
  - sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
  - echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)"
