language: python

matrix:
  include:
    - python: 2.7
      env: KERAS_BACKEND=theano

notifications:
  email: false

before_install:
  - wget https://repo.continuum.io/archive/Anaconda2-4.3.0-Linux-x86_64.sh -O anaconda.sh
  - chmod 777 *
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - conda create -y -n temp python=2.7 anaconda
  - source activate temp
  - conda install --yes -n temp pyyaml
  - conda install --yes -n temp HDF5
  - conda install --yes -n temp h5py
  - conda install --yes -n temp -c rdonnelly libgpuarray
  - conda install --yes -n temp -c rdonnelly pygpu
  - conda install --yes -n temp -c rdonnelly theano
  - conda install --yes -n temp -c conda-forge theano=0.8*
  - conda install --yes -n temp -c conda-forge keras=1.2*
  - conda install --yes -n temp scikit-learn=0.17*
  - conda install --yes -n temp -c rdkit rdkit-postgresql
  - conda install --yes -n temp -c r rpy2
  - conda install --yes -n temp -c bioconda r-prroc=1.1
  - conda install --yes -n temp -c auto croc
  - conda install --yes -n temp pip

install:
  - $HOME/anaconda/bin/pip install -e .

script:
  - python -c "import keras.backend"
  - sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
  - echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)"
  - python test/test_gpu.py

after_script:
  - source deactivate
  - conda remove -n temp -all