name: pria
channels:
- bioconda
- r
- rdkit
- conda-forge
- defaults
dependencies:
- python=2.7
- setuptools
- pyyaml
- h5py
- theano=0.8
- keras=1.2
- scikit-learn=0.17
- rdkit-postgresql=2016.03.4
- rpy2=2.8.5
- r-prroc=1.1
- pandas
- sympy
- pip:
  - croc==1.1.26
